<!--<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\FinalProject.Core\FinalProject.Core.csproj" />
	</ItemGroup>
</Project>-->
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework> <!-- שים לב לשינוי כאן -->
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>10.0</LangVersion> <!-- הוסף את השורה הזו -->
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.3">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FinalProject.Core\FinalProject.Core.csproj" />
	</ItemGroup>
</Project>
