<!--<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.7" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FinalProject.Core\FinalProject.Core.csproj" />
	</ItemGroup>
</Project>-->
<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>10.0</LangVersion>
		<!-- הוסף את השורה הזו -->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FinalProject.Core\FinalProject.Core.csproj" />
		<ProjectReference Include="..\FinalProject.Data\FinalProject.Data.csproj" />
		<ProjectReference Include="..\FinalProject.Service\FinalProject.Service.csproj" />
	</ItemGroup>
</Project>
